name: 🔥 Full Auto-Setup for test_repo_-2

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  init-files:
    name: 🛠 Create CODEOWNERS & PR Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create required files
        run: |
          mkdir -p .github
          echo "*   @softservedata" > .github/CODEOWNERS
          cat <<'EOF' > .github/pull_request_template.md
          ## Describe your changes
          -

          ## Issue ticket number and link
          -

          ## Checklist before requesting a review
          - [ ] I have performed a self-review of my code
          - [ ] If it is a core feature, I have added thorough tests
          - [ ] Do we need to implement analytics?
          - [ ] Will this be part of a product update? If yes, describe briefly
          EOF

      - name: Commit and push templates
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .github/CODEOWNERS .github/pull_request_template.md
          git commit -m "Automated: Added CODEOWNERS & PR template" || echo "No changes"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/fubukipod/test_repo_-2 HEAD:main

  invite-collaborator:
    name: 🤝 Invite softservedata
    runs-on: ubuntu-latest
    needs: init-files
    steps:
      - name: Send collaborator invite
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/fubukipod/test_repo_-2/collaborators/softservedata
          data: '{"permission":"push"}'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  create-develop:
    name: 🌱 Ensure develop branch & set default
    runs-on: ubuntu-latest
    needs: invite-collaborator
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create develop if missing
        run: |
          if ! git ls-remote --heads https://x-access-token:${{ secrets.PAT }}@github.com/fubukipod/test_repo_-2 develop | grep develop; then
            echo "Creating develop branch..."
            git checkout -b develop
            git push https://x-access-token:${{ secrets.PAT }}@github.com/fubukipod/test_repo_-2 develop
          else
            echo "Develop branch already exists."
          fi

      - name: Set develop as default
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/fubukipod/test_repo_-2
          data: '{"default_branch":"develop"}'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  branch-protection:
    name: 🔒 Apply Branch Protection Rules
    runs-on: ubuntu-latest
    needs: create-develop
    steps:
      - name: Protect main (1 approval)
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/fubukipod/test_repo_-2/branches/main/protection
          mediaType: '{"previews": ["luke-cage"]}'
          data: |
            required_pull_request_reviews:
              required_approving_review_count: 1
            enforce_admins: true
            restrictions: null
            required_status_checks: null
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Protect develop (2 approvals)
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/fubukipod/test_repo_-2/branches/develop/protection
          mediaType: '{"previews": ["luke-cage"]}'
          data: |
            required_pull_request_reviews:
              required_approving_review_count: 2
            enforce_admins: true
            restrictions: null
            required_status_checks: null
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  add-deploy-key:
    name: 🔑 Add Deploy Key
    runs-on: ubuntu-latest
    needs: branch-protection
    steps:
      - name: Generate key
        run: |
          ssh-keygen -t rsa -b 4096 -C "deploy_key" -f deploy_key -N ""
          echo "PRIVATE_KEY<<EOF" >> $GITHUB_ENV
          cat deploy_key >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload key
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/fubukipod/test_repo_-2/keys
          data: |
            {
              "title": "DEPLOY_KEY",
              "key": "$(cat deploy_key.pub)",
              "read_only": false
            }
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  create-project:
    name: 📋 Create Project Board
    runs-on: ubuntu-latest
    needs: add-deploy-key
    steps:
      - name: Create project
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/fubukipod/test_repo_-2/projects
          mediaType: '{"previews": ["inertia"]}'
          data: '{"name":"Automated Project","body":"Board created by GitHub Action"}'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  notify-discord:
    name: 📢 Discord PR Notification
    runs-on: ubuntu-latest
    needs: create-project
    steps:
      - name: Send Discord Message
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            🚀 **New PR in test_repo_-2**
            🔹 Title: ${{ github.event.pull_request.title }}
            👤 Author: ${{ github.actor }}
            🔗 Link: ${{ github.event.pull_request.html_url }}
